### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by viocha** [thomanq/math-snippets#1]
How can I use this plug-in? after typing abs, !! and other shortcuts in the markdown file, there is no response.

**Comment by thomanq** [comment]
Hi :)

1) Install [Markdown+Math](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath) in addition to this extension.
2) Create a Markdown file (with .md extension)
3) Use the snippets from this extension to write math.
For example `ii` expands to `$$` and `abs` expands to `\left|  \right|`.
This extension contains snippets that expand to LaTeX. It's important to write valid LaTeX for it to work.
Use the snippets to write something like `$\left| x-2 \right|$`. (No space between the dollar signs and the content).

4) Use the built-in Markdown Preview (Ctrl+Shift+P : Markdown: Open Preview to the Side) to preview the results.
The side pane should show: <img src="https://render.githubusercontent.com/render/math?math=\left| x-2 \right|">

**Comment by viocha** [comment]
thanks. and i find the suggestions show only when there is space after the dollar sign
![image](https://user-images.githubusercontent.com/66580331/115182732-0fffc800-a10d-11eb-8499-f67959d10e08.png)
![image](https://user-images.githubusercontent.com/66580331/115182819-358cd180-a10d-11eb-9e8e-26c598d9aef8.png)
![image](https://user-images.githubusercontent.com/66580331/115182846-49d0ce80-a10d-11eb-9f36-12976bf2ff81.png)

**Comment by thomanq** [comment]
This is VS Code's behavior. The extension includes only snippets, it doesn't dictate when they are shown. :)
