### ISSUE TITLE
align does not work

### ISSUE THREAD

**Issue by sleepycat233** [thomanq/math-snippets#2]
![image](https://user-images.githubusercontent.com/77555918/221362850-0b0d45d1-7dea-4b6c-a895-ad0f9db3056a.png)
![image](https://user-images.githubusercontent.com/77555918/221362854-7eb635cd-ff12-481d-8948-84229d7b9dba.png)

**Comment by thomanq** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/7536471/222086351-6c7b5b84-b95a-4e15-b9f9-6ee1117938e5.png">

Hi @sleepycat233,
 
 I cannot reproduce the behavior described above.
